# Generated by Django 4.1.7 on 2023-03-08 16:18

from django.db import migrations, models
import warehouse.models.category


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "wallpaper",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=warehouse.models.category.wallpapers_categories,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
