# Generated by Django 4.1.7 on 2023-03-10 11:46

from django.db import migrations, models
import django.db.models.deletion
import warehouse.models.category
import warehouse.models.product_media


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("url", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "wallpaper",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to=warehouse.models.category.wallpapers_categories,
                    ),
                ),
                (
                    "show_online",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to show or not this category on the website",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.SlugField(unique=True)),
                ("short_description", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "price_start_at",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the price start at a fixed amount but can vary",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "price_offer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "service",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this product is a service or not",
                    ),
                ),
                (
                    "show_online",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to show or not this product on the website",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.productattribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.productattributevalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media",
                    models.ImageField(
                        upload_to=warehouse.models.product_media.products_media_dir
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="warehouse.product",
                    ),
                ),
            ],
        ),
    ]
