# Generated by Django 4.1.7 on 2023-03-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0003_productattribute_productattributevalue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="attribute",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="warehouse.productattributevalue",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ProductVariantAttribute",
        ),
    ]
