# Generated by Django 4.1.7 on 2023-03-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0004_productvariant_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_online",
            field=models.BooleanField(
                default=True,
                help_text="Whether to show or not this category on the website",
            ),
        ),
    ]
