# Generated by Django 4.1.7 on 2023-03-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0005_category_show_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmedia",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="warehouse.product",
            ),
        ),
    ]
