#!/bin/sh

rm -rf webapp/client/static/client
rm -rf webapp/client/templates/client

mkdir -p webapp/client/static/client
mkdir -p webapp/client/templates/client

cp -a client/dist/index.html webapp/client/templates/client/index.html
cp -a client/dist/static/client webapp/client/static/