name: larapida
services:
  webapp:
    container_name: larapida-webapp
    build: .
    volumes:
      - ./data/media:/home/public/media
      - ./data/static:/home/public/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=$SECRET_KEY
      - PRODUCTION=0
      - DEBUG=1
      - DEFAULT_EMAIL_FROM=$DEFAULT_EMAIL_FROM
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_HOST_USER=$EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD

  db:
    container_name: larapida-db
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
