name: larapida
services:
  webapp:
    container_name: larapida-webapp
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: larapida-db
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
