[tool.poetry]
name = "larapida"
version = "3.0.0"
description = "La Rapida di Davide Di Criscito's website"
authors = ["Davide Di Criscito <davide.dicriscito@gmail.com>"]
readme = "README.md"
homepage = "https://larapidamolinetto.com"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1"
gunicorn = "^20.1.0"


[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
isort = "^5.10.1"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
