# Generated by Django 4.1 on 2022-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utente",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="utente",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
