# Generated by Django 4.1.7 on 2023-03-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "address",
                    models.CharField(
                        help_text="The full address of the store including city, zip and country",
                        max_length=255,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social",
                    models.CharField(
                        choices=[
                            ("FACEBOOK", "Facebook"),
                            ("INSTAGRAM", "Instagram"),
                            ("TIKTOK", "TikTok"),
                            ("TWITTER", "Twitter"),
                            ("WHATSAPP", "Whatsapp"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.CharField(max_length=20)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.store"
                    ),
                ),
            ],
        ),
    ]
