# Generated by Django 4.1.7 on 2023-03-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="fax",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="mobile",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
