# Generated by Django 4.1 on 2022-08-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NegozioOrari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "giorno",
                    models.CharField(
                        choices=[
                            ("1", "Lunedì"),
                            ("2", "Martedì"),
                            ("3", "Mercoledì"),
                            ("4", "Giovedì"),
                            ("5", "Venerdì"),
                            ("6", "Sabato"),
                            ("7", "Domenica"),
                        ],
                        max_length=3,
                    ),
                ),
                ("aperto", models.BooleanField(default=True)),
                ("dalle", models.TimeField()),
                ("alle", models.TimeField()),
            ],
            options={
                "verbose_name_plural": "Negozio Orari",
                "ordering": ["giorno"],
            },
        ),
        migrations.CreateModel(
            name="NegozioOrariSpeciali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("giorno", models.DateField()),
                ("aperto", models.BooleanField(default=False)),
                ("dalle", models.TimeField(blank=True, null=True)),
                ("alle", models.TimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Negozio Orari Speciali",
                "ordering": ["giorno"],
            },
        ),
    ]
