# Generated by Django 4.1.7 on 2023-03-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_business_fax_alter_business_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
