# Generated by Django 4.1.7 on 2023-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0003_business_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="email",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
