# Generated by Django 4.0.5 on 2022-06-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url', models.SlugField(unique=True)),
                ('sito', models.BooleanField(default=True, verbose_name='Mostra sul sito')),
                ('descrizione_breve', models.TextField(max_length=500)),
                ('descrizione', models.TextField(blank=True, default=None)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='CategoriaSecondaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sito', models.BooleanField(default=True, verbose_name='Mostra sul sito')),
                ('descrizione', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_secondaria', to='magazzino.categoria')),
            ],
        ),
    ]
