# Generated by Django 4.0.5 on 2022-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magazzino", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriasecondaria",
            options={
                "verbose_name": "Categoria Secondaria",
                "verbose_name_plural": "Categorie Secondarie",
            },
        ),
    ]
