# Generated by Django 4.1 on 2022-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazzino", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prodotto",
            name="url",
            field=models.SlugField(default="/", unique=True),
            preserve_default=False,
        ),
    ]
