# Generated by Django 4.0.5 on 2022-06-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazzino", "0002_alter_categoriasecondaria_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdottoAttributo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributo", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Prodotto Attributi",
            },
        ),
        migrations.CreateModel(
            name="ProdottoAttributoValore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valore", models.CharField(max_length=100)),
                (
                    "attributo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magazzino.prodottoattributo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prodotto Attributo Valori",
            },
        ),
    ]
