# Generated by Django 4.0.5 on 2022-06-09 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("magazzino", "0004_prodotto"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="ProdottoVariante",
            fields=[
                (
                    "prodotto_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="magazzino.prodotto",
                    ),
                ),
                (
                    "attributo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magazzino.prodottoattributovalore",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prodotto Varianti",
            },
            bases=("magazzino.prodotto",),
        ),
    ]
