# Generated by Django 4.0.5 on 2022-06-09 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0005_prodotto_polymorphic_ctype_prodottovariante'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodottovariante',
            name='prodotto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variante', to='magazzino.prodotto'),
            preserve_default=False,
        ),
    ]
