# Generated by Django 4.0.5 on 2022-06-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0006_prodottovariante_prodotto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodottovariante',
            name='attributo',
        ),
        migrations.CreateModel(
            name='ProdottoVarianteAttributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazzino.prodottoattributovalore')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazzino.prodottovariante')),
            ],
            options={
                'verbose_name_plural': 'Prodotto Variante Attributi',
            },
        ),
    ]
