# Generated by Django 4.0.5 on 2022-06-25 08:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazzino", "0008_categoria_wallpaper_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prodotto",
            options={
                "ordering": ("nome",),
                "verbose_name": "Prodotto",
                "verbose_name_plural": "Prodotti",
            },
        ),
        migrations.AddField(
            model_name="prodotto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magazzino.categoria",
            ),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="categoria_secondaria",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="magazzino.categoriasecondaria",
            ),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="descrizione",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="descrizione_breve",
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="shop",
            field=models.BooleanField(default=True, help_text="mostra sullo shop"),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="sito",
            field=models.BooleanField(default=True, help_text="mostra sul sito"),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="url",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="prodotto",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="nome",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
