# Generated by Django 4.0.5 on 2022-06-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazzino', '0010_prodotto_prezzo_prodotto_prezzo_a_partire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
