# Generated by Django 4.0.5 on 2022-06-25 13:41

import django.db.models.deletion
import magazzino.helpers.updirs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazzino", "0011_alter_prodotto_nome"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProdottoImmagine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(upload_to=magazzino.helpers.updirs.art_file_dir),
                ),
                ("ogimage", models.BooleanField(default=False)),
                ("thumbnail", models.BooleanField(default=False)),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immagini",
                        to="magazzino.prodotto",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Prodotto Immagini",
            },
        ),
    ]
