# Generated by Django 4.0.5 on 2022-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magazzino", "0012_prodottoimmagine"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="servizio",
            field=models.BooleanField(
                default=False, help_text="Questo prodotto è un servizio"
            ),
        ),
    ]
