name: Deploy

on:
  push:
    tags:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: bahmutov/npm-install@v1
      - run: npm run collectclient

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ctrlmaniac
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.40

      - name: Export requirements
        run: poetry export -f requirements.txt --output requirements.txt

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ctrlmaniac/larapida:latest,ctrlmaniac/larapida:${{ env.RELEASE_VERSION }}

      - name: run docker stack deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: docker stack deploy -c larapida.yaml larapida
